<?php

namespace Database\Seeders;

use App\Models\BidangLomba;
use App\Models\BidangMataKuliah;
use App\Models\MataKuliah;
use App\Models\Prodi;
use Illuminate\Database\Seeder;

class BidangMataKuliahSeeder extends Seeder
{
    public function run(): void
    {
        $prodis = Prodi::pluck('id', 'singkatan')->toArray();
        $bidangs = BidangLomba::pluck('id', 'nama')->toArray();

        $mappings = [
            ['bidang' => 'Kewirausahaan', 'prodi' => 'SI', 'kode_mk' => 'MKI9007'],
            ['bidang' => 'Kewirausahaan', 'prodi' => 'SI', 'kode_mk' => 'KSI1408'],
            ['bidang' => 'Kewirausahaan', 'prodi' => 'TI', 'kode_mk' => 'MKI9007'],
            ['bidang' => 'Kewirausahaan', 'prodi' => 'TI', 'kode_mk' => 'KTU1053'],
            ['bidang' => 'Kewirausahaan', 'prodi' => 'TI', 'kode_mk' => 'KTU1055'],
            ['bidang' => 'Kewirausahaan', 'prodi' => 'IF', 'kode_mk' => 'MKI9007'],
            ['bidang' => 'VGK', 'prodi' => 'SI', 'kode_mk' => 'KSI1413'],
            ['bidang' => 'VGK', 'prodi' => 'TI', 'kode_mk' => 'KSI1413'],
            ['bidang' => 'VGK', 'prodi' => 'IF', 'kode_mk' => 'KSI1413'],
            ['bidang' => 'UI/UX', 'prodi' => 'SI', 'kode_mk' => 'KSU1107'],
            ['bidang' => 'UI/UX', 'prodi' => 'SI', 'kode_mk' => 'KMU1010'],
            ['bidang' => 'UI/UX', 'prodi' => 'SI', 'kode_mk' => 'KMU1042'],
            ['bidang' => 'UI/UX', 'prodi' => 'SI', 'kode_mk' => 'KIU1047'],
            ['bidang' => 'UI/UX', 'prodi' => 'TI', 'kode_mk' => 'KST1205'],
            ['bidang' => 'UI/UX', 'prodi' => 'TI', 'kode_mk' => 'KST1304'],
            ['bidang' => 'UI/UX', 'prodi' => 'TI', 'kode_mk' => 'KMU1010'],
            ['bidang' => 'UI/UX', 'prodi' => 'TI', 'kode_mk' => 'KMU1042'],
            ['bidang' => 'UI/UX', 'prodi' => 'IF', 'kode_mk' => 'KSU1107'],
            ['bidang' => 'UI/UX', 'prodi' => 'IF', 'kode_mk' => 'KMU1010'],
            ['bidang' => 'UI/UX', 'prodi' => 'IF', 'kode_mk' => 'KMU1042'],
            ['bidang' => 'Programming', 'prodi' => 'SI', 'kode_mk' => 'KSU1104'],
            ['bidang' => 'Programming', 'prodi' => 'SI', 'kode_mk' => 'KSU1206'],
            ['bidang' => 'Programming', 'prodi' => 'SI', 'kode_mk' => 'KSU1208'],
            ['bidang' => 'Programming', 'prodi' => 'SI', 'kode_mk' => 'KSI1412'],
            ['bidang' => 'Programming', 'prodi' => 'SI', 'kode_mk' => 'KMU1012'],
            ['bidang' => 'Programming', 'prodi' => 'SI', 'kode_mk' => 'KSI1409'],
            ['bidang' => 'Programming', 'prodi' => 'TI', 'kode_mk' => 'KST1102'],
            ['bidang' => 'Programming', 'prodi' => 'TI', 'kode_mk' => 'KST1204'],
            ['bidang' => 'Programming', 'prodi' => 'TI', 'kode_mk' => 'KST1407'],
            ['bidang' => 'Programming', 'prodi' => 'TI', 'kode_mk' => 'KST1510'],
            ['bidang' => 'Programming', 'prodi' => 'TI', 'kode_mk' => 'KMU1012'],
            ['bidang' => 'Programming', 'prodi' => 'IF', 'kode_mk' => 'KSF1102'],
            ['bidang' => 'Programming', 'prodi' => 'IF', 'kode_mk' => 'KSF1205'],
            ['bidang' => 'Programming', 'prodi' => 'IF', 'kode_mk' => 'KSU1208'],
            ['bidang' => 'Programming', 'prodi' => 'IF', 'kode_mk' => 'KSF1409'],
            ['bidang' => 'Programming', 'prodi' => 'IF', 'kode_mk' => 'KMU1012'],
            ['bidang' => 'Programming', 'prodi' => 'IF', 'kode_mk' => 'KSI1409'],
            ['bidang' => 'Programming', 'prodi' => 'IF', 'kode_mk' => 'KSF1418'],
            ['bidang' => 'Software Development', 'prodi' => 'SI', 'kode_mk' => 'KSU1205'],
            ['bidang' => 'Software Development', 'prodi' => 'SI', 'kode_mk' => 'KSI1302'],
            ['bidang' => 'Software Development', 'prodi' => 'SI', 'kode_mk' => 'KSI1306'],
            ['bidang' => 'Software Development', 'prodi' => 'SI', 'kode_mk' => 'KSU1501'],
            ['bidang' => 'Software Development', 'prodi' => 'TI', 'kode_mk' => 'KSU1205'],
            ['bidang' => 'Software Development', 'prodi' => 'TI', 'kode_mk' => 'KST1404'],
            ['bidang' => 'Software Development', 'prodi' => 'TI', 'kode_mk' => 'KSU1501'],
            ['bidang' => 'Software Development', 'prodi' => 'IF', 'kode_mk' => 'KSU1205'],
            ['bidang' => 'Software Development', 'prodi' => 'IF', 'kode_mk' => 'KSF1401'],
            ['bidang' => 'Software Development', 'prodi' => 'IF', 'kode_mk' => 'KSU1501'],
            ['bidang' => 'Karya Tulis Ilmiah', 'prodi' => 'SI', 'kode_mk' => 'KSU1601'],
            ['bidang' => 'Karya Tulis Ilmiah', 'prodi' => 'SI', 'kode_mk' => 'KSI1413'],
            ['bidang' => 'Karya Tulis Ilmiah', 'prodi' => 'TI', 'kode_mk' => 'KSU1601'],
            ['bidang' => 'Karya Tulis Ilmiah', 'prodi' => 'IF', 'kode_mk' => 'KSF1513'],
            ['bidang' => 'Matematika Komputasi', 'prodi' => 'SI', 'kode_mk' => 'KSU1207'],
            ['bidang' => 'Matematika Komputasi', 'prodi' => 'SI', 'kode_mk' => 'KSU1101'],
            ['bidang' => 'Matematika Komputasi', 'prodi' => 'TI', 'kode_mk' => 'KSU1207'],
            ['bidang' => 'Matematika Komputasi', 'prodi' => 'TI', 'kode_mk' => 'KSU1101'],
            ['bidang' => 'Matematika Komputasi', 'prodi' => 'TI', 'kode_mk' => 'KST1410'],
            ['bidang' => 'Matematika Komputasi', 'prodi' => 'IF', 'kode_mk' => 'KSU1207'],
            ['bidang' => 'Matematika Komputasi', 'prodi' => 'IF', 'kode_mk' => 'KSU1101'],
            ['bidang' => 'Matematika Komputasi', 'prodi' => 'IF', 'kode_mk' => 'KSF1412'],
            ['bidang' => 'Matematika Komputasi', 'prodi' => 'IF', 'kode_mk' => 'KSF1101'],
            ['bidang' => 'Immersive Development', 'prodi' => 'SI', 'kode_mk' => 'KSU1104'],
            ['bidang' => 'Immersive Development', 'prodi' => 'SI', 'kode_mk' => 'KSU1206'],
            ['bidang' => 'Immersive Development', 'prodi' => 'SI', 'kode_mk' => 'KSU1208'],
            ['bidang' => 'Immersive Development', 'prodi' => 'SI', 'kode_mk' => 'KSI1412'],
            ['bidang' => 'Immersive Development', 'prodi' => 'SI', 'kode_mk' => 'KMU1012'],
            ['bidang' => 'Immersive Development', 'prodi' => 'SI', 'kode_mk' => 'KFU1016'],
            ['bidang' => 'Immersive Development', 'prodi' => 'SI', 'kode_mk' => 'KSU1205'],
            ['bidang' => 'Immersive Development', 'prodi' => 'SI', 'kode_mk' => 'KSI1302'],
            ['bidang' => 'Immersive Development', 'prodi' => 'SI', 'kode_mk' => 'KSI1306'],
            ['bidang' => 'Immersive Development', 'prodi' => 'TI', 'kode_mk' => 'KST1102'],
            ['bidang' => 'Immersive Development', 'prodi' => 'TI', 'kode_mk' => 'KST1204'],
            ['bidang' => 'Immersive Development', 'prodi' => 'TI', 'kode_mk' => 'KST1407'],
            ['bidang' => 'Immersive Development', 'prodi' => 'TI', 'kode_mk' => 'KST1510'],
            ['bidang' => 'Immersive Development', 'prodi' => 'TI', 'kode_mk' => 'KMU1012'],
            ['bidang' => 'Immersive Development', 'prodi' => 'TI', 'kode_mk' => 'KTU1042'],
            ['bidang' => 'Immersive Development', 'prodi' => 'TI', 'kode_mk' => 'KSU1205'],
            ['bidang' => 'Immersive Development', 'prodi' => 'TI', 'kode_mk' => 'KST1404'],
            ['bidang' => 'Immersive Development', 'prodi' => 'TI', 'kode_mk' => 'KTU1044'],
            ['bidang' => 'Immersive Development', 'prodi' => 'IF', 'kode_mk' => 'KSF1102'],
            ['bidang' => 'Immersive Development', 'prodi' => 'IF', 'kode_mk' => 'KSF1205'],
            ['bidang' => 'Immersive Development', 'prodi' => 'IF', 'kode_mk' => 'KSU1208'],
            ['bidang' => 'Immersive Development', 'prodi' => 'IF', 'kode_mk' => 'KSF1409'],
            ['bidang' => 'Immersive Development', 'prodi' => 'IF', 'kode_mk' => 'KMU1012'],
            ['bidang' => 'Immersive Development', 'prodi' => 'IF', 'kode_mk' => 'KSI1409'],
            ['bidang' => 'Immersive Development', 'prodi' => 'IF', 'kode_mk' => 'KSF1418'],
            ['bidang' => 'Immersive Development', 'prodi' => 'IF', 'kode_mk' => 'KFU1527'],
            ['bidang' => 'Immersive Development', 'prodi' => 'IF', 'kode_mk' => 'KSU1205'],
            ['bidang' => 'Immersive Development', 'prodi' => 'IF', 'kode_mk' => 'KSF1401'],
            ['bidang' => 'KKN', 'prodi' => 'SI', 'kode_mk' => 'UNU9003'],
            ['bidang' => 'KKN', 'prodi' => 'TI', 'kode_mk' => 'UNU9003'],
            ['bidang' => 'KKN', 'prodi' => 'IF', 'kode_mk' => 'UNU9003'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'SI', 'kode_mk' => 'KTU1024'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'SI', 'kode_mk' => 'KTU1025'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'SI', 'kode_mk' => 'KTU1026'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'SI', 'kode_mk' => 'KTU1027'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'SI', 'kode_mk' => 'KTU1028'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'TI', 'kode_mk' => 'KTU1024'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'TI', 'kode_mk' => 'KTU1025'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'TI', 'kode_mk' => 'KTU1026'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'TI', 'kode_mk' => 'KTU1027'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'TI', 'kode_mk' => 'KTU1028'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'TI', 'kode_mk' => 'KTU1031'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'IF', 'kode_mk' => 'KTU1024'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'IF', 'kode_mk' => 'KTU1025'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'IF', 'kode_mk' => 'KTU1026'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'IF', 'kode_mk' => 'KTU1027'],
            ['bidang' => 'Embedded dan IOT', 'prodi' => 'IF', 'kode_mk' => 'KTU1028'],
            ['bidang' => 'Jaringan dan Sekuritas', 'prodi' => 'SI', 'kode_mk' => 'KSI1308'],
            ['bidang' => 'Jaringan dan Sekuritas', 'prodi' => 'SI', 'kode_mk' => 'KSU1303'],
            ['bidang' => 'Jaringan dan Sekuritas', 'prodi' => 'TI', 'kode_mk' => 'KTU1011'],
            ['bidang' => 'Jaringan dan Sekuritas', 'prodi' => 'TI', 'kode_mk' => 'KTU1012'],
            ['bidang' => 'Jaringan dan Sekuritas', 'prodi' => 'TI', 'kode_mk' => 'KTU1014'],
            ['bidang' => 'Jaringan dan Sekuritas', 'prodi' => 'TI', 'kode_mk' => 'KTU1015'],
            ['bidang' => 'Jaringan dan Sekuritas', 'prodi' => 'TI', 'kode_mk' => 'KTU1016'],
            ['bidang' => 'Jaringan dan Sekuritas', 'prodi' => 'TI', 'kode_mk' => 'KTU1017'],
            ['bidang' => 'Jaringan dan Sekuritas', 'prodi' => 'IF', 'kode_mk' => 'MKI1309'],
            ['bidang' => 'Jaringan dan Sekuritas', 'prodi' => 'IF', 'kode_mk' => 'KFU1508'],
            ['bidang' => 'Jaringan dan Sekuritas', 'prodi' => 'IF', 'kode_mk' => 'KSF1206'],
            ['bidang' => 'Jaringan dan Sekuritas', 'prodi' => 'IF', 'kode_mk' => 'KFU1515'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'SI', 'kode_mk' => 'MKI9007'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'SI', 'kode_mk' => 'KSI1408'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'SI', 'kode_mk' => 'KSU1104'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'SI', 'kode_mk' => 'KSU1206'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'SI', 'kode_mk' => 'KSU1208'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'SI', 'kode_mk' => 'KSI1412'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'SI', 'kode_mk' => 'KMU1012'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'SI', 'kode_mk' => 'KSI1409'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'SI', 'kode_mk' => 'KSU1601'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'SI', 'kode_mk' => 'KSI1413'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'SI', 'kode_mk' => 'UNU9003'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'TI', 'kode_mk' => 'MKI9007'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'TI', 'kode_mk' => 'KTU1053'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'TI', 'kode_mk' => 'KTU1055'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'TI', 'kode_mk' => 'KSF1506'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'TI', 'kode_mk' => 'UNU9003'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'TI', 'kode_mk' => 'KST1102'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'TI', 'kode_mk' => 'KST1204'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'TI', 'kode_mk' => 'KST1407'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'TI', 'kode_mk' => 'KST1510'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'TI', 'kode_mk' => 'KMU1012'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'TI', 'kode_mk' => 'KSU1601'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'IF', 'kode_mk' => 'MKI9007'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'IF', 'kode_mk' => 'KSF1102'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'IF', 'kode_mk' => 'KSF1205'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'IF', 'kode_mk' => 'KSU1208'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'IF', 'kode_mk' => 'KSF1409'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'IF', 'kode_mk' => 'KMU1012'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'IF', 'kode_mk' => 'KSI1409'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'IF', 'kode_mk' => 'KSF1418'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'IF', 'kode_mk' => 'UNU9003'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'IF', 'kode_mk' => 'KFU1204'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'IF', 'kode_mk' => 'KSF1513'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'IF', 'kode_mk' => 'KSF1506'],
            ['bidang' => 'PPK Ormawa', 'prodi' => 'IF', 'kode_mk' => 'KSU1501'],
            ['bidang' => 'BMC', 'prodi' => 'SI', 'kode_mk' => 'MKI9007'],
            ['bidang' => 'BMC', 'prodi' => 'SI', 'kode_mk' => 'KIU1023'],
        ];

        foreach ($mappings as $map) {
            if (!isset($bidangs[$map['bidang']]) || !isset($prodis[$map['prodi']])) {
                continue;
            }
            $bidangId = $bidangs[$map['bidang']];
            $prodiId = $prodis[$map['prodi']];
            $mk = MataKuliah::where('prodi_id', $prodiId)->where('kode_mk', $map['kode_mk'])->first();
            if ($mk) {
                BidangMataKuliah::firstOrCreate(
                    ['bidang_id' => $bidangId, 'mata_kuliah_id' => $mk->id],
                    ['is_active' => 1]
                );
            }
        }
    }
}
